version: 0.0
os: linux

#files:
# You can specify one or more mappings in the files section.
#  - source: /
#    destination: /var/www/html/WordPress

hooks:
 # The lifecycle hooks sections allows you to specify deployment scripts.

#  ApplicationStop:
  # Step 1: Stop Apache and MySQL if running.
#      - location: helper_scripts/stop_server.sh

  BeforeInstall:
  # Step 2: Install Apache and MySQL.
  # You can specify one or more scripts per deployment lifecycle event.
      - location: deploy_hooks/puppet-apply-apache.sh
      - location: deploy_hooks/puppet-apply-mysql.sh

   AfterInstall:
  # Step 3: Set permissions.
      - location: deploy_hooks /change_permissions.sh
        timeout: 30
        runas: root
  # Step 4: Start the server.
      - location: helper_scripts/start_server.sh
        timeout: 30
        runas: root

